const TAG_23_CASE = "case";
const TAG_23_UNLESS = "unless"
const TAG_23_SET_VALUE = "set_value";
const TAG_23_DEFAULT_VALUE = "default_value";
const TAG_23_PRINT = "print";
const TAG_23_EVALUATED = "evaluated"
const TAG_23_FOR = "for";
const  TAG_23_IN = "in";
const TAG_23_INDEX = "index";
const  TAG_23_KEY = "key"
const TAG_23_DESTROY = "destroy";
const TAG_23_HIDE ="none";
const  TAG_23_SHOW = "block";
const TAG_23_OBJECT ="Object";
const TAG_23_ARRAY ="Array";
const  TAG_23_TRUE = "true";
const TAG_23_FOR_NOT_PROVIDED = "for value not provided";
const TAG_23_IN_NOT_PRIVODE = "in not provided";
const  TAG_23_LOAD = "load";
const TAG_23_START = "Tag23Start";

